const common = require('../utils/common')
const math = require('../utils/math')
const random = require('../utils/random')

const run = (client, msg, args) => {
  // Get subject from args.
  const subject = common.stripMentions(args.join(' '), msg)

  // Ramdom intro.
  const intro = random.exclamation()

  // Ramdom adjective.
  const adjectives = [
    'Aesthetic',
    'Aromatic',
    'Beautiful',
    'Caramelised',
    'Carefully Crafted',
    'Classy',
    'Crisp',
    'Delicious',
    'Dripping',
    'Famous',
    'Fantastic',
    'Fleshy',
    'Fluffy',
    'Fragant',
    'Fragile',
    'Fresh',
    'Fruity',
    'Funny Looking',
    'Generous',
    'Giant',
    'Gourmet',
    'Grandma\'s',
    'Heart Shaped',
    'Heavenly',
    'Homemade',
    'Iconic',
    'Intense',
    'Intricate',
    'Juicy',
    'Lively',
    'Lovely',
    'Luscious',
    'Mini',
    'Next Level',
    'Rainbow',
    'Squishy',
    'Sparkling',
    'Spicy',
    'Sprinkled',
    'Sticky',
    'Top Tier',
    'Traditional',
    'Triple Layered',
    'Ultimate'
  ]
  const adjective = math.getRandomStringFromArray(adjectives)

  // Ramdom flavour.
  const flavours = [
    'Almond & Honey',
    'Almond Liqueur',
    'Amaretto',
    'Bacon',
    'Baileys',
    'Butter-Stuffed',
    'Butterscotch Liqueur',
    'Cherry',
    'Chocolate',
    'Chocolate Bark',
    'Chocolate Chip',
    'Chocolate Hazelnut',
    'Cinamon-Honey',
    'Cocktail',
    'Cranberry',
    'Cream',
    'Dewberry',
    'Eggnog-dipped',
    'Elderberry',
    'Gingerbread',
    'Ginseng',
    'Honey',
    'Japanese Milk',
    'Kahlúa',
    'Loganberry',
    'Macchiato',
    'Maltesers',
    'Martini',
    'Mint',
    'Nutella',
    'Oreo',
    'Peanut Butter',
    'Peppermint',
    'Pistachio',
    'Poppyseed',
    'Rice',
    'Raspberry',
    'Red Berry',
    'Red Wine',
    'Honey Rum',
    'Salted Caramel',
    'Salted Toffee',
    'Tiramisu',
    'Vanilla',
    'Walnut',
    'White and Golden Raspberry',
    'White Chocolate'
  ]
  const flavour = math.getRandomStringFromArray(flavours)

  // Ramdom treat.
  const treats = [
    ['🍎', 'Apple Crisp'],
    ['🍎', 'Apple Pockets'],
    ['🥯', 'Bagels'],
    ['🍞', 'Banana Bread'],
    ['🍞', 'Bread'],
    ['🍞', 'Brioche Bread'],
    ['🍞', 'Melon Bread'],
    ['🍞', 'Tartine Bread'],
    ['🧁', 'Crème Brûlée'],
    ['🍫', 'Brownies'],
    ['🍰', 'Angel Food Cakes'],
    ['🍰', 'Cakes'],
    ['🍬', 'Candy'],
    ['🍰', 'Cheese Cake'],
    ['🍪', 'Cookies'],
    ['🥥', 'Coconuts'],
    ['🥐', 'Croissants'],
    ['🧁', 'Cupcakes'],
    ['🍩', 'Doughnuts'],
    ['🍕', 'Fruit Pizza'],
    ['🥚', 'Poached Eggs'],
    ['🥠', 'Fortune Cookies'],
    ['🍦', 'Icecream'],
    ['🍋', 'Lemon Meringue'],
    ['🍭', 'Lollipops'],
    ['🧁', 'Macaroons'],
    ['🥝', 'Kiwis'],
    ['🍈', 'Melon'],
    ['🥮', 'Moon Cakes'],
    ['🧁', 'Mousse Cups'],
    ['🧁', 'Muffins'],
    ['🥞', 'Pancakes'],
    ['🍍', 'Pineapple Cobbler'],
    ['🍍', 'Pineapple Whip'],
    ['🥧', 'Pie'],
    ['🥨', 'Pretzels'],
    ['🍐', 'Poached Pears'],
    ['🥭', 'Poached Mangos'],
    ['🍮', 'Pudding'],
    ['🍨', 'Trifles'],
    ['🍘', 'Rice Crackers'],
    ['🍠', 'Sweet Potatoes'],
    ['🍓', 'Strawberry Fluff'],
    ['🧇', 'Waffles'],
    ['🍉', 'Watermelon']
  ]
  const treat = math.getRandomStringFromArray(treats)

  msg.channel.send(`${intro} ${msg.author.username} is treating **${subject}** to...\n${treat[0]} **${adjective} ${flavour} ${treat[1]}!**`)

  // IHAA... If subject is Korean Lady she will react with a random emote.
  if (subject.toLowerCase() === 'koreanlady' || subject.toLowerCase() === 'korean lady') {
    // Ramdom emote reaction.
    const reactions = [
      ['peepoPants', '🥳'],
      ['apollo20Wow', '😍'],
      ['apolPat', '🤗'],
      ['apolLove', '❤️'],
      ['apolHyper', '😋'],
      ['POG', '😮'],
      ['ihaa', '🥰']
    ]
    const reaction = math.getRandomStringFromArray(reactions)

    // React with custom emote or its associated fallback if necessary.
    common.reactWithCustomEmote(client, msg, reaction[0], reaction[1])
  }
}

module.exports = {
  name: 'treat',
  desc: 'Give someone a treat.\n\nTreats are randomly generated by a super secret special algorithm, only with the highest quality ingredients. By being gifted a treat you enter a non-negotiable contract and are legally obligated to stop what you are doing and eat. Treats may contain traces of pineapple.',
  aliases: ['dessert'],
  usage: 'treat <subject>',
  examples: ['treat @KoreanLady', 'treat everyone'],
  args: true,
  args_error: 'You must specify who you want to give your precious treat!',
  run
}
